# test-project - GPLANG Project
# Generated by GAP v1.0.0

import std.time

func main():
    print("🚀 Welcome to test-project!")
    print("Built with GPLANG - Python syntax, C performance!")
    
    var start_time = Time.now()
    
    # Your code here
    parallel for i in range(1000000):
        var result = i * 2 + 1
    
    var duration = Time.now() - start_time
    print("Processed 1M operations in: " + str(duration.milliseconds()) + "ms")
    
    return 0
